// String-keyed icons, so data (the module registry, search hit kinds) can name
// an icon without importing React components.

import {
  ArrowDownUp,
  TriangleAlert,
  Route,
  BadgeCheck,
  Bell,
  Blocks,
  BookOpenText,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  Circle,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  Earth,
  Globe,
  HandCoins,
  Handshake,
  History,
  HousePlus,
  Tent,
  IdCard,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Magnet,
  Map,
  Megaphone,
  PaintRoller,
  Palette,
  Plug,
  Receipt,
  ReceiptText,
  Rocket,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Tags,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
  Workflow,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  building: Building2,
  "house-plus": HousePlus,
  tent: Tent,
  alert: TriangleAlert,
  route: Route,
  map: Map,
  workflow: Workflow,
  landmark: Landmark,
  rocket: Rocket,
  briefcase: Briefcase,
  handshake: Handshake,
  users: Users,
  calendar: CalendarDays,
  tags: Tags,
  history: History,
  wrench: Wrench,
  roller: PaintRoller,
  inbox: Inbox,
  phone: Smartphone,
  megaphone: Megaphone,
  transfer: ArrowDownUp,
  clipboard: ClipboardList,
  magnet: Magnet,
  door: DoorOpen,
  card: CreditCard,
  ledger: BookOpenText,
  coins: HandCoins,
  bill: ReceiptText,
  calculator: Calculator,
  receipt: Receipt,
  chart: ChartColumn,
  clock: Clock,
  "id-card": IdCard,
  timesheet: CalendarClock,
  trending: TrendingUp,
  key: KeyRound,
  palette: Palette,
  globe: Globe,
  earth: Earth,
  bell: Bell,
  plug: Plug,
  "user-cog": UserCog,
  wallet: Wallet,
  blocks: Blocks,
  settings: Settings,
  scroll: ScrollText,
  shield: Shield,
  "shield-check": ShieldCheck,
  badge: BadgeCheck,
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp aria-hidden strokeWidth={1.75} {...props} />;
}
