// ---------------------------------------------------------------------------
// Permission catalog (seeded into `permission`)
// ---------------------------------------------------------------------------

/// UI/seed metadata for one permission.
pub struct PermissionMeta {
    pub key: &'static str,
    pub category: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    /// `platform`, `tenant`, or `both`.
    pub scope: &'static str,
}

/// The full catalog, grouped by category. Seeded so the dashboard can present a
/// permission picker; custom permissions can be appended in the DB later.
pub const PERMISSION_CATALOG: &[PermissionMeta] = &[
    PermissionMeta {
        key: "property:read",
        category: "Properties",
        label: "View properties",
        description: "View the portfolio and property profiles.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "property:write",
        category: "Properties",
        label: "Edit properties",
        description: "Create, onboard, and edit properties.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "entity:read",
        category: "Properties",
        label: "View entities",
        description: "View the entities registry (banks, lenders, contractors).",
        scope: "tenant",
    },
    PermissionMeta {
        key: "entity:manage",
        category: "Properties",
        label: "Manage entities",
        description: "Create and edit registry entities and their notes.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "finance:read",
        category: "Properties",
        label: "View financing",
        description: "View property mortgages, loans, and equity.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "finance:manage",
        category: "Properties",
        label: "Manage financing",
        description: "Add and edit property mortgages and loans.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "lease:read",
        category: "Rentals",
        label: "View rentals",
        description: "View units, leases/tenancies, and the rent ledger.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "lease:manage",
        category: "Rentals",
        label: "Manage rentals",
        description: "Create and edit units, leases, and record payments.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "fee:read",
        category: "Rentals",
        label: "View fee schedule",
        description: "View the fee / discount / amenity catalog.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "fee:manage",
        category: "Rentals",
        label: "Manage fee schedule",
        description: "Configure conditional fees, discounts, rebates, and amenities.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "vehicle:read",
        category: "Rentals",
        label: "View vehicles",
        description: "View resident vehicle profiles.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "vehicle:manage",
        category: "Rentals",
        label: "Manage vehicles",
        description: "Add and edit resident vehicle profiles.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "maintenance:read",
        category: "Rentals",
        label: "View maintenance",
        description: "View maintenance tickets / work orders.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "maintenance:manage",
        category: "Rentals",
        label: "Manage maintenance",
        description: "Create, assign, and resolve maintenance tickets.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "title:read",
        category: "Properties",
        label: "View title",
        description: "View ownership (deed) and liens / encumbrances.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "title:manage",
        category: "Properties",
        label: "Manage title",
        description: "Edit ownership records and liens.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "listing:read",
        category: "Leasing",
        label: "View listings",
        description: "View public listings.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "listing:write",
        category: "Leasing",
        label: "Edit listings",
        description: "Create and edit listings.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "application:read",
        category: "Leasing",
        label: "View applications",
        description: "View rental applications.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "application:write",
        category: "Leasing",
        label: "Manage applications",
        description: "Advance / decide on applications.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "theme:write",
        category: "Settings",
        label: "Edit branding",
        description: "Edit white-label branding and legal templates.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "apitoken:manage",
        category: "Settings",
        label: "Manage API tokens",
        description: "Issue and revoke vendor API tokens.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "billing:read",
        category: "Billing",
        label: "View billing",
        description: "View invoices and plan usage.",
        scope: "both",
    },
    PermissionMeta {
        key: "tenant:manage",
        category: "Settings",
        label: "Manage workspace",
        description: "Edit workspace settings and modules.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "user:read",
        category: "Access",
        label: "View users",
        description: "View user accounts.",
        scope: "both",
    },
    PermissionMeta {
        key: "user:manage",
        category: "Access",
        label: "Manage users",
        description: "Create, edit, suspend user accounts.",
        scope: "both",
    },
    PermissionMeta {
        key: "profile:read",
        category: "Access",
        label: "View profiles",
        description: "View user profiles (non-sensitive fields).",
        scope: "both",
    },
    PermissionMeta {
        key: "profile:write",
        category: "Access",
        label: "Edit profiles",
        description: "Edit user profile details.",
        scope: "both",
    },
    PermissionMeta {
        key: "profile:read_pii",
        category: "Access",
        label: "View sensitive PII",
        description: "Decrypt and view SSN / government IDs. Highly privileged.",
        scope: "both",
    },
    PermissionMeta {
        key: "member:read",
        category: "Access",
        label: "View members",
        description: "View workspace members and personas.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "member:manage",
        category: "Access",
        label: "Manage members",
        description: "Invite, assign personas, and remove members.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "role:read",
        category: "Access",
        label: "View roles",
        description: "View roles and their permissions.",
        scope: "both",
    },
    PermissionMeta {
        key: "role:manage",
        category: "Access",
        label: "Manage roles",
        description: "Create roles and edit their permissions.",
        scope: "both",
    },
    PermissionMeta {
        key: "audit:read",
        category: "Access",
        label: "View audit log",
        description: "View the security audit trail (PII reveals, role/user changes).",
        scope: "both",
    },
    PermissionMeta {
        key: "domain:read",
        category: "Settings",
        label: "View domains",
        description: "View white-label domains and their verification / TLS status.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "domain:manage",
        category: "Settings",
        label: "Manage domains",
        description: "Add custom domains, verify DNS, and set audiences.",
        scope: "tenant",
    },
    PermissionMeta {
        key: "platform:impersonate",
        category: "Platform",
        label: "Impersonate tenants",
        description: "Begin an audited, time-boxed impersonation session into a client workspace.",
        scope: "platform",
    },
    PermissionMeta {
        key: "platform:admin",
        category: "Platform",
        label: "Platform administrator",
        description: "Full cross-tenant administration (Acre HQ). Implies every permission.",
        scope: "platform",
    },
];
