// ---------------------------------------------------------------------------
// System roles (seeded into `role` + `role_permission`)
// ---------------------------------------------------------------------------

use super::permission::Permission::{self, *};
use super::permission::{ALL_PERMS, SCOPE_PLATFORM, SCOPE_TENANT};

/// A built-in role definition: a named permission bundle at a given scope.
pub struct SystemRole {
    pub key: &'static str,
    pub scope: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub permissions: &'static [Permission],
}

/// Tenant-admin permission bundle (everything within a workspace).
const TENANT_FULL: &[Permission] = &[
    PropertyRead,
    PropertyWrite,
    EntityRead,
    EntityManage,
    FinanceRead,
    FinanceManage,
    LeaseRead,
    LeaseManage,
    FeeRead,
    FeeManage,
    VehicleRead,
    VehicleManage,
    MaintenanceRead,
    MaintenanceManage,
    MessageRead,
    MessageManage,
    TitleRead,
    TitleManage,
    ListingRead,
    ListingWrite,
    ApplicationRead,
    ApplicationWrite,
    ScreeningRead,
    ThemeWrite,
    DomainRead,
    DomainManage,
    ApiTokenManage,
    IntegrationsManage,
    DocumentRead,
    DocumentManage,
    BillingRead,
    LedgerRead,
    LedgerManage,
    PaymentRead,
    PaymentManage,
    PayoutManage,
    PayableRead,
    PayableManage,
    PayableApprove,
    CalendarRead,
    CalendarManage,
    TenantManage,
    UserRead,
    ProfileRead,
    ProfileWrite,
    MemberRead,
    MemberManage,
    RoleRead,
    RoleManage,
];

/// The seeded system roles. Acre personas are platform-scoped; client personas
/// are tenant-scoped. The dashboard can clone or extend these.
pub const SYSTEM_ROLES: &[SystemRole] = &[
    // ---- Platform (Acre HQ) ----
    SystemRole {
        key: "acre_admin",
        scope: SCOPE_PLATFORM,
        name: "Acre Admin",
        description: "Full cross-tenant platform administration.",
        permissions: ALL_PERMS,
    },
    SystemRole {
        key: "acre_account_manager",
        scope: SCOPE_PLATFORM,
        name: "Account Manager",
        description: "Manage client accounts, users, and access.",
        permissions: &[
            TenantManage,
            UserRead,
            UserManage,
            ProfileRead,
            MemberRead,
            MemberManage,
            RoleRead,
            BillingRead,
            PropertyRead,
            ApplicationRead,
            AuditRead,
            ImpersonateTenant,
        ],
    },
    SystemRole {
        key: "acre_support",
        scope: SCOPE_PLATFORM,
        name: "Support Agent",
        description: "Assist clients; view workspaces and users.",
        permissions: &[
            UserRead,
            ProfileRead,
            MemberRead,
            RoleRead,
            PropertyRead,
            ListingRead,
            ApplicationRead,
            TenantManage,
            ImpersonateTenant,
        ],
    },
    SystemRole {
        key: "acre_billing",
        scope: SCOPE_PLATFORM,
        name: "Billing Specialist",
        description: "Manage plans, invoices, and billing.",
        permissions: &[BillingRead, UserRead, ProfileRead],
    },
    SystemRole {
        key: "acre_read_only",
        scope: SCOPE_PLATFORM,
        name: "Acre Read-only",
        description: "Read-only platform access for audit / analytics.",
        permissions: &[
            UserRead,
            ProfileRead,
            MemberRead,
            RoleRead,
            PropertyRead,
            ListingRead,
            ApplicationRead,
            BillingRead,
            AuditRead,
        ],
    },
    // ---- Tenant (client workspace) ----
    SystemRole {
        key: "tenant_owner",
        scope: SCOPE_TENANT,
        name: "Workspace Owner",
        description: "Full control of the client workspace.",
        permissions: TENANT_FULL,
    },
    SystemRole {
        key: "property_manager",
        scope: SCOPE_TENANT,
        name: "Property Manager",
        description: "Day-to-day property and leasing operations.",
        permissions: &[
            PropertyRead,
            PropertyWrite,
            EntityRead,
            EntityManage,
            FinanceRead,
            FinanceManage,
            LeaseRead,
            LeaseManage,
            FeeRead,
            FeeManage,
            VehicleRead,
            VehicleManage,
            MaintenanceRead,
            MaintenanceManage,
            MessageRead,
            MessageManage,
            TitleRead,
            TitleManage,
            ListingRead,
            ListingWrite,
            ApplicationRead,
            ApplicationWrite,
            ScreeningRead,
            MemberRead,
            RoleRead,
            ThemeWrite,
            DocumentRead,
            DocumentManage,
            LedgerRead,
            PaymentRead,
            PaymentManage,
            PayableRead,
            PayableManage,
            CalendarRead,
            CalendarManage,
        ],
    },
    SystemRole {
        key: "back_office",
        scope: SCOPE_TENANT,
        name: "Back-office Staff",
        description: "Applications, billing, and administrative work.",
        permissions: &[
            PropertyRead,
            LeaseRead,
            LeaseManage,
            FeeRead,
            FeeManage,
            VehicleRead,
            VehicleManage,
            MaintenanceRead,
            MessageRead,
            MessageManage,
            ApplicationRead,
            ApplicationWrite,
            ScreeningRead,
            BillingRead,
            MemberRead,
            UserRead,
            ProfileRead,
            DocumentRead,
            DocumentManage,
            LedgerRead,
            LedgerManage,
            PaymentRead,
            PaymentManage,
            PayoutManage,
            PayableRead,
            PayableManage,
            PayableApprove,
            CalendarRead,
            CalendarManage,
        ],
    },
    SystemRole {
        key: "leasing_agent",
        scope: SCOPE_TENANT,
        name: "Leasing Agent",
        description: "Manage listings and the applicant pipeline.",
        permissions: &[
            PropertyRead,
            ListingRead,
            ListingWrite,
            ApplicationRead,
            ApplicationWrite,
            ScreeningRead,
            LeaseRead,
            FeeRead,
            VehicleRead,
            VehicleManage,
            CalendarRead,
            CalendarManage,
        ],
    },
    SystemRole {
        key: "maintenance",
        scope: SCOPE_TENANT,
        name: "Maintenance",
        description: "View properties and manage work orders.",
        permissions: &[
            PropertyRead,
            LeaseRead,
            MaintenanceRead,
            MaintenanceManage,
            CalendarRead,
        ],
    },
    SystemRole {
        key: "landlord",
        scope: SCOPE_TENANT,
        name: "Landlord / Owner",
        description: "Owner view of their managed properties and leasing.",
        permissions: &[
            PropertyRead,
            PropertyWrite,
            EntityRead,
            FinanceRead,
            LeaseRead,
            FeeRead,
            FeeManage,
            VehicleRead,
            MaintenanceRead,
            MessageRead,
            TitleRead,
            ListingRead,
            ListingWrite,
            ApplicationRead,
            DocumentRead,
            LedgerRead,
            PaymentRead,
            PayableRead,
            CalendarRead,
        ],
    },
    SystemRole {
        key: "renter",
        scope: SCOPE_TENANT,
        name: "Renter",
        description: "Resident / applicant portal access. Renters browse the \
                      public website and use the /my/* self-service routes, so \
                      they hold no console-read permissions (listing:read would \
                      expose unpublished drafts via GET /listings).",
        permissions: &[VehicleRead, VehicleManage],
    },
];
