//! The **job kits** every workspace starts with. Each is something to do
//! ("Replace dishwasher", "Run a new circuit"), not a symptom: a symptom ("AC
//! not cooling") can have many causes, so it's a work order that gets a kit
//! once someone has looked. Kits are keyed, so a workspace can rename, change
//! or retire one and keep it that way, and new kits in a later release still
//! reach every workspace.
//!
//! The six kits from the first release were named for the job too
//! ("Shower replacement"); migration 065 gave them their keys and new names.
//!
//! Parts carry typical costs and no store links: the console offers a search
//! at Home Depot, Lowe's and Amazon for every part, and a workspace pastes
//! the exact product it buys into its own kit.

pub struct Kit {
    /// Stable across renames: what seeding matches on.
    pub key: &'static str,
    pub name: &'static str,
    pub area: &'static str,
    pub category: &'static str,
    pub priority: &'static str,
    pub description: &'static str,
    /// `(title, trade, minutes, needs a contractor)`.
    pub tasks: &'static [(&'static str, &'static str, i32, bool)],
    /// `(name, quantity, typical unit cost in cents)`.
    pub parts: &'static [(&'static str, i32, i64)],
}

pub const KITS: &[Kit] = &[
    Kit {
        key: "replace-shower",
        name: "Replace shower",
        area: "Bathroom",
        category: "plumbing",
        priority: "normal",
        description: "Tear out the old shower, check the framing and valve, hang \
                      cement board, waterproof, and set a new surround and trim.",
        tasks: &[
            ("Shut off water and protect the room", "general", 30, false),
            ("Demo old surround and haul debris", "demo", 240, false),
            ("Inspect framing and studs for rot", "carpentry", 45, false),
            (
                "Replace shower valve and supply lines",
                "plumbing",
                180,
                true,
            ),
            (
                "Hang cement board and drywall around the shower",
                "drywall",
                180,
                false,
            ),
            ("Tape, mud and sand the drywall", "drywall", 240, false),
            (
                "Waterproof membrane over the cement board",
                "tile",
                120,
                false,
            ),
            ("Install the new surround or tile", "tile", 480, false),
            ("Set trim, shower head and handle", "plumbing", 60, true),
            ("Caulk, touch up paint and clean", "paint", 120, false),
            ("Pressure test and final walkthrough", "plumbing", 30, true),
        ],
        parts: &[
            ("Shower valve, pressure-balance", 1, 14_900),
            ("Shower trim kit", 1, 12_900),
            ("Shower surround kit", 1, 54_900),
            ("Cement board 3x5", 4, 1_450),
            ("Drywall 4x8 1/2in moisture-resistant", 2, 1_850),
            ("Joint compound", 1, 1_600),
            ("Drywall tape", 1, 600),
            ("Waterproofing membrane", 1, 8_900),
            ("PEX pipe 1/2in, 10 ft", 2, 850),
            ("PEX fittings and crimp rings", 1, 2_400),
            ("Silicone caulk, kitchen and bath", 2, 900),
            ("Cement board screws", 1, 1_100),
            ("Contractor bags", 1, 2_200),
        ],
    },
    Kit {
        key: "replace-toilet",
        name: "Replace toilet",
        area: "Bathroom",
        category: "plumbing",
        priority: "normal",
        description: "Pull the old toilet, check the flange and subfloor, set a new one.",
        tasks: &[
            ("Shut off and drain the toilet", "plumbing", 15, false),
            ("Remove the old toilet and wax ring", "plumbing", 30, false),
            ("Inspect flange and subfloor", "carpentry", 20, false),
            (
                "Set the new toilet on a new wax ring",
                "plumbing",
                45,
                false,
            ),
            ("Connect supply and test for leaks", "plumbing", 20, false),
            ("Caulk the base and clean up", "cleaning", 15, false),
        ],
        parts: &[
            ("Toilet, elongated 1.28 gpf", 1, 21_900),
            ("Wax ring with sleeve", 1, 800),
            ("Closet bolts", 1, 500),
            ("Toilet supply line 12in", 1, 900),
            ("Silicone caulk, kitchen and bath", 1, 900),
        ],
    },
    Kit {
        key: "replace-water-heater",
        name: "Replace water heater",
        area: "Utility",
        category: "plumbing",
        priority: "high",
        description: "Swap the tank: drain, remove, set the new heater with a pan \
                      and expansion tank, connect, and test.",
        tasks: &[
            (
                "Shut off gas or power and water, drain the tank",
                "plumbing",
                45,
                false,
            ),
            ("Remove and haul the old heater", "demo", 60, false),
            (
                "Set the new heater, pan and expansion tank",
                "plumbing",
                120,
                true,
            ),
            (
                "Connect water, gas or electric, and venting",
                "plumbing",
                90,
                true,
            ),
            ("Fill, purge air, light and test", "plumbing", 30, true),
            ("Check the permit and seismic straps", "general", 20, false),
        ],
        parts: &[
            ("Water heater, 50 gal", 1, 89_900),
            ("Expansion tank", 1, 5_500),
            ("Water heater drain pan", 1, 3_200),
            ("Flex water connector", 2, 1_600),
            ("Seismic strap kit", 1, 3_400),
            ("Gas flex line", 1, 2_800),
        ],
    },
    Kit {
        key: "patch-drywall",
        name: "Patch and paint drywall",
        area: "Any room",
        category: "structural",
        priority: "low",
        description: "Cut out the damage, patch, match the texture and paint.",
        tasks: &[
            ("Cut out the damaged drywall", "drywall", 30, false),
            ("Patch, tape and mud, three coats", "drywall", 180, false),
            ("Sand and match the texture", "drywall", 60, false),
            ("Prime and paint", "paint", 90, false),
        ],
        parts: &[
            ("Drywall 4x8 1/2in", 1, 1_600),
            ("Joint compound", 1, 1_600),
            ("Drywall tape", 1, 600),
            ("Primer, 1 qt", 1, 1_800),
            ("Interior paint, 1 gal", 1, 4_200),
            ("Sanding sponge", 2, 400),
        ],
    },
    Kit {
        key: "repaint-unit",
        name: "Repaint a unit (turnover)",
        area: "Whole unit",
        category: "general",
        priority: "normal",
        description: "Repaint a vacant unit: patch, prime, two coats on walls, trim and doors.",
        tasks: &[
            ("Patch nail holes and dings", "drywall", 90, false),
            ("Mask and protect floors", "paint", 60, false),
            ("Prime stains", "paint", 60, false),
            ("Paint walls, two coats", "paint", 600, false),
            ("Paint trim and doors", "paint", 240, false),
            ("Clean up and touch up", "cleaning", 90, false),
        ],
        parts: &[
            ("Interior paint, 5 gal", 1, 17_900),
            ("Primer, 1 gal", 1, 3_200),
            ("Spackle", 1, 900),
            ("Painter's tape", 3, 700),
            ("Drop cloth", 2, 1_500),
            ("Roller cover", 4, 600),
        ],
    },
    Kit {
        key: "service-hvac",
        name: "Service HVAC (seasonal)",
        area: "Mechanical",
        category: "hvac",
        priority: "normal",
        description: "Spring and fall service: filter, coil, refrigerant, drain line, thermostat.",
        tasks: &[
            ("Replace the air filter", "hvac", 15, false),
            ("Clean the condenser coil", "hvac", 45, false),
            ("Check refrigerant and electrical", "hvac", 45, true),
            ("Flush the condensate line", "hvac", 20, false),
            (
                "Test the thermostat and run a full cycle",
                "hvac",
                20,
                false,
            ),
        ],
        parts: &[
            ("Air filter 16x25x1 MERV 8", 1, 1_200),
            ("Condensate line tablets", 1, 900),
            ("Coil cleaner", 1, 1_400),
        ],
    },
    Kit {
        key: "replace-dishwasher",
        name: "Replace dishwasher",
        area: "Kitchen",
        category: "appliance",
        priority: "normal",
        description: "Pull the old dishwasher, check the valve and drain, set and connect the new one, and run a test cycle.",
        tasks: &[
            ("Shut off water and power to the dishwasher", "general", 10, false),
            ("Disconnect and pull the old dishwasher", "appliance", 30, false),
            ("Check the supply valve and drain connection", "plumbing", 15, false),
            ("Set, level and secure the new dishwasher", "appliance", 45, false),
            ("Connect water, drain and power", "plumbing", 30, false),
            ("Run a test cycle and check for leaks", "appliance", 30, false),
            ("Haul away the old unit", "cleaning", 20, false),
        ],
        parts: &[
            ("Dishwasher, 24 in built-in", 1, 54900),
            ("Dishwasher installation kit", 1, 2500),
            ("Dishwasher power cord", 1, 1800),
            ("Hose clamp", 1, 400),
        ],
    },
    Kit {
        key: "replace-thermostat",
        name: "Replace thermostat",
        area: "Hallway",
        category: "hvac",
        priority: "normal",
        description: "Swap the thermostat for a programmable or smart one, adding a C wire adapter where there isn't one.",
        tasks: &[
            ("Turn off power to the HVAC system", "general", 5, false),
            ("Label the wires and remove the old thermostat", "hvac", 15, false),
            ("Check for a C wire; add an adapter if there isn't one", "electrical", 20, false),
            ("Mount the base and connect the wires", "hvac", 20, false),
            ("Power up, set up and test heat, cool and fan", "hvac", 20, false),
            ("Show the resident how it works", "general", 10, false),
        ],
        parts: &[
            ("Programmable thermostat", 1, 14900),
            ("C-wire adapter", 1, 2500),
            ("Thermostat wall plate", 1, 900),
        ],
    },
    Kit {
        key: "run-new-circuit",
        name: "Run a new circuit",
        area: "Any room",
        category: "electrical",
        priority: "normal",
        description: "Pull a permit, run a new 20 A circuit from the panel, inspect, and patch the walls.",
        tasks: &[
            ("Pull the electrical permit", "general", 30, false),
            ("Map the run and check panel capacity", "electrical", 45, true),
            ("Cut access holes along the run", "drywall", 60, false),
            ("Pull wire from the panel to the new box", "electrical", 180, true),
            ("Install the breaker, box and device", "electrical", 60, true),
            ("Rough-in inspection", "electrical", 30, true),
            ("Patch and paint the access holes", "drywall", 120, false),
            ("Final inspection and label the panel", "electrical", 30, true),
        ],
        parts: &[
            ("12/2 NM-B cable, 50 ft", 1, 9800),
            ("20 A breaker", 1, 1500),
            ("Old-work electrical box", 2, 300),
            ("20 A outlet", 1, 400),
            ("Outlet cover plate", 1, 200),
        ],
    },
    Kit {
        key: "replace-outlet",
        name: "Replace an outlet (GFCI where required)",
        area: "Any room",
        category: "electrical",
        priority: "normal",
        description: "Swap a dead or worn outlet, using a GFCI in kitchens, baths, laundry and outside.",
        tasks: &[
            ("Turn off the breaker and test the outlet dead", "electrical", 10, false),
            ("Pull the old outlet and check the wiring", "electrical", 15, false),
            ("Wire and mount the new outlet", "electrical", 20, false),
            ("Restore power and test, including GFCI trip", "electrical", 10, false),
        ],
        parts: &[
            ("GFCI outlet, 15 A", 1, 2200),
            ("Tamper-resistant outlet, 15 A", 1, 300),
            ("Outlet cover plate", 1, 200),
        ],
    },
    Kit {
        key: "replace-light-fixture",
        name: "Replace light fixture",
        area: "Any room",
        category: "electrical",
        priority: "low",
        description: "Take down the old fixture, check the box, and hang and wire the new one.",
        tasks: &[
            ("Turn off the breaker and test dead", "electrical", 10, false),
            ("Remove the old fixture", "electrical", 15, false),
            ("Check the box is rated for the fixture", "electrical", 10, false),
            ("Mount and wire the new fixture", "electrical", 30, false),
            ("Add bulbs, test and clean up", "general", 10, false),
        ],
        parts: &[
            ("Light fixture", 1, 6900),
            ("LED bulb", 2, 500),
            ("Wire connectors, pack", 1, 400),
        ],
    },
    Kit {
        key: "install-ceiling-fan",
        name: "Install ceiling fan",
        area: "Bedroom",
        category: "electrical",
        priority: "low",
        description: "Replace a light with a ceiling fan on a fan-rated box.",
        tasks: &[
            ("Turn off the breaker and test dead", "electrical", 10, false),
            ("Remove the old fixture", "electrical", 15, false),
            ("Install a fan-rated box and brace", "electrical", 45, false),
            ("Assemble and hang the fan", "electrical", 60, false),
            ("Wire the fan and light", "electrical", 30, false),
            ("Balance and test every speed", "electrical", 15, false),
        ],
        parts: &[
            ("Ceiling fan, 52 in", 1, 14900),
            ("Fan-rated box with brace", 1, 2500),
        ],
    },
    Kit {
        key: "replace-garbage-disposal",
        name: "Replace garbage disposal",
        area: "Kitchen",
        category: "plumbing",
        priority: "normal",
        description: "Swap the disposal, reconnect the drain and dishwasher line, and test.",
        tasks: &[
            ("Turn off power and unplug the disposal", "general", 5, false),
            ("Disconnect the drain and dishwasher line", "plumbing", 20, false),
            ("Remove the old unit", "plumbing", 15, false),
            ("Mount the new unit and connect the drain", "plumbing", 40, false),
            ("Knock out the dishwasher plug if needed", "plumbing", 5, false),
            ("Run it and check for leaks", "plumbing", 10, false),
        ],
        parts: &[
            ("Garbage disposal, 1/2 HP", 1, 12900),
            ("Plumber's putty", 1, 500),
            ("Disposal power cord", 1, 1500),
        ],
    },
    Kit {
        key: "replace-kitchen-faucet",
        name: "Replace kitchen faucet",
        area: "Kitchen",
        category: "plumbing",
        priority: "normal",
        description: "Take out the old faucet and install a new one with new supply lines.",
        tasks: &[
            ("Shut off the supply valves", "plumbing", 5, false),
            ("Disconnect and remove the old faucet", "plumbing", 30, false),
            ("Clean the sink deck", "general", 10, false),
            ("Install the new faucet and supply lines", "plumbing", 45, false),
            ("Flush the lines and check for leaks", "plumbing", 15, false),
        ],
        parts: &[
            ("Kitchen faucet, pull-down", 1, 17900),
            ("Supply line", 2, 900),
            ("Plumber's putty", 1, 500),
        ],
    },
    Kit {
        key: "replace-faucet-cartridge",
        name: "Replace faucet cartridge",
        area: "Kitchen / bath",
        category: "plumbing",
        priority: "normal",
        description: "Stop a drip: swap the cartridge and the supply lines.",
        tasks: &[
            ("Shut off the water", "plumbing", 5, false),
            ("Remove the handle and old cartridge", "plumbing", 15, false),
            ("Install the new cartridge", "plumbing", 15, false),
            ("Test for drips under load", "plumbing", 10, false),
        ],
        parts: &[
            ("Faucet cartridge", 1, 1800),
            ("Supply line", 2, 900),
        ],
    },
    Kit {
        key: "rebuild-toilet-tank",
        name: "Rebuild toilet tank",
        area: "Bathroom",
        category: "plumbing",
        priority: "normal",
        description: "Replace the fill valve, flapper and supply line on a running toilet.",
        tasks: &[
            ("Shut off and drain the tank", "plumbing", 5, false),
            ("Replace the fill valve", "plumbing", 20, false),
            ("Replace the flapper and chain", "plumbing", 15, false),
            ("Set the water level and test flush three times", "plumbing", 10, false),
        ],
        parts: &[
            ("Toilet fill valve", 1, 1200),
            ("Toilet flapper", 1, 800),
            ("Supply line", 1, 900),
        ],
    },
    Kit {
        key: "snake-drain",
        name: "Snake a drain",
        area: "Kitchen / bath",
        category: "plumbing",
        priority: "normal",
        description: "Clear a slow or blocked drain with an auger and check the trap.",
        tasks: &[
            ("Clear and protect the area", "general", 10, false),
            ("Pull the trap or open the clean-out", "plumbing", 15, false),
            ("Run the auger", "plumbing", 30, false),
            ("Flush with hot water and check the flow", "plumbing", 10, false),
            ("Reassemble and check for leaks", "plumbing", 10, false),
        ],
        parts: &[
            ("P-trap kit", 1, 1200),
        ],
    },
    Kit {
        key: "replace-smoke-co-detectors",
        name: "Replace smoke and CO detectors",
        area: "Hallway / bedrooms",
        category: "electrical",
        priority: "high",
        description: "Replace alarms past ten years, put fresh batteries in the rest, and log the dates.",
        tasks: &[
            ("Test every alarm and note its date", "general", 15, false),
            ("Replace alarms older than ten years", "electrical", 30, false),
            ("Put fresh batteries in the rest", "general", 15, false),
            ("Test every alarm and log the dates", "general", 15, false),
        ],
        parts: &[
            ("Smoke and CO combination alarm", 2, 3900),
            ("9 V batteries, 4-pack", 1, 1200),
        ],
    },
    Kit {
        key: "replace-hvac-filter",
        name: "Replace HVAC filter",
        area: "HVAC",
        category: "hvac",
        priority: "low",
        description: "Swap the filter, date it, and check the condensate line.",
        tasks: &[
            ("Check the filter size", "hvac", 5, false),
            ("Swap the filter and write the date on it", "hvac", 10, false),
            ("Check the condensate line", "hvac", 10, false),
        ],
        parts: &[
            ("Air filter 16x25x1 MERV 8", 1, 1200),
        ],
    },
    Kit {
        key: "rekey-locks",
        name: "Rekey locks",
        area: "Entry",
        category: "general",
        priority: "high",
        description: "Rekey the entry locks between residents, replacing a worn deadbolt.",
        tasks: &[
            ("Rekey the entry door locks", "general", 30, false),
            ("Replace a damaged or worn deadbolt", "carpentry", 30, false),
            ("Test every key in every door", "general", 10, false),
            ("Log the new keys and hand them over", "general", 10, false),
        ],
        parts: &[
            ("Lock rekey kit", 1, 1500),
            ("Deadbolt, single cylinder", 1, 3500),
        ],
    },
    Kit {
        key: "replace-refrigerator",
        name: "Replace refrigerator",
        area: "Kitchen",
        category: "appliance",
        priority: "high",
        description: "Swap the refrigerator, reconnect the ice maker line, and check it holds temperature.",
        tasks: &[
            ("Empty and unplug the old unit", "general", 15, false),
            ("Disconnect the ice maker line", "plumbing", 10, false),
            ("Remove the old refrigerator", "appliance", 30, false),
            ("Place, level and connect the new one", "appliance", 45, false),
            ("Test ice and water; check the temperature next day", "appliance", 15, false),
            ("Haul away the old unit", "cleaning", 20, false),
        ],
        parts: &[
            ("Refrigerator, 30 in top-freezer", 1, 89900),
            ("Ice maker water line kit", 1, 2000),
        ],
    },
    Kit {
        key: "replace-range",
        name: "Replace range",
        area: "Kitchen",
        category: "appliance",
        priority: "normal",
        description: "Swap the range, fit the anti-tip bracket, and connect power or gas (leak-tested).",
        tasks: &[
            ("Unplug, or shut off the gas", "general", 10, false),
            ("Remove the old range", "appliance", 30, false),
            ("Install the anti-tip bracket", "carpentry", 15, false),
            ("Connect power or gas and leak-test the gas", "appliance", 30, false),
            ("Test every burner and the oven", "appliance", 15, false),
            ("Haul away the old unit", "cleaning", 20, false),
        ],
        parts: &[
            ("Range, 30 in", 1, 69900),
            ("Anti-tip bracket", 1, 1500),
            ("Range power cord, 4-wire", 1, 3000),
        ],
    },
    Kit {
        key: "recaulk-tub-and-sinks",
        name: "Re-caulk tub and sinks",
        area: "Bathroom",
        category: "plumbing",
        priority: "low",
        description: "Cut out old caulk, clean, and run new silicone at the tub, shower and sinks.",
        tasks: &[
            ("Cut out the old caulk", "tile", 30, false),
            ("Clean and dry the joints", "cleaning", 20, false),
            ("Caulk the tub, shower and sinks", "tile", 40, false),
            ("Let it cure and wipe down", "cleaning", 10, false),
        ],
        parts: &[
            ("Silicone caulk, kitchen and bath", 2, 900),
            ("Caulk remover", 1, 800),
        ],
    },
    Kit {
        key: "replace-blinds",
        name: "Replace window blinds",
        area: "Any room",
        category: "general",
        priority: "low",
        description: "Measure, take down the old blinds, and hang new ones.",
        tasks: &[
            ("Measure the windows", "general", 15, false),
            ("Take down the old blinds", "general", 15, false),
            ("Hang the new blinds", "general", 40, false),
            ("Test and clean up", "general", 10, false),
        ],
        parts: &[
            ("Faux-wood blinds", 2, 3500),
        ],
    },
    Kit {
        key: "pressure-wash-exterior",
        name: "Pressure-wash walkways and exterior",
        area: "Exterior",
        category: "general",
        priority: "low",
        description: "Protect the plants and openings, then wash the walkways, stairs and siding.",
        tasks: &[
            ("Protect plants, doors and windows", "exterior", 15, false),
            ("Wash the walkways and stairs", "exterior", 90, true),
            ("Wash the siding", "exterior", 120, true),
            ("Rinse and walk through", "exterior", 15, false),
        ],
        parts: &[
            ("Surface cleaner solution", 1, 3000),
        ],
    },
    Kit {
        key: "replace-flooring-lvp",
        name: "Replace flooring (LVP)",
        area: "Any room",
        category: "structural",
        priority: "normal",
        description: "Pull the old flooring, prep the subfloor, lay luxury vinyl plank, and finish the trim.",
        tasks: &[
            ("Move furniture and protect the room", "general", 30, false),
            ("Remove the old flooring", "demo", 120, false),
            ("Level and prep the subfloor", "flooring", 90, false),
            ("Lay the vinyl plank", "flooring", 360, false),
            ("Fit baseboard, quarter-round and transitions", "carpentry", 120, false),
            ("Clean up", "cleaning", 30, false),
        ],
        parts: &[
            ("Luxury vinyl plank, box", 8, 5500),
            ("Underlayment roll", 1, 4500),
            ("Transition strip", 2, 2500),
            ("Quarter-round, 8 ft", 6, 900),
        ],
    },
];
